### ISSUE TITLE
Clients in floating layout tag aren't restored

### ISSUE THREAD

**Issue by motdef** [guotsuan/awesome-revelation#21]
I'm using the master branch of Awesome and clients in a floating tag retain their positions from the Revelation view after either selecting a window or cancelling. Tiled clients and floating clients within tiled tags are correctly restored to their original positions.

**Comment by guotsuan** [comment]
Sorry for the later reply. I tried the awesome from the latest master branch. I have no problems with restoring the clients in floating. However, I think it could happy, because there could be some properties of those clients are not saved by revelation. Therefore those properties will not be restored. Do you give some specific properties to the floating layout?

**Comment by ShadOoW** [comment]
Hello,

I've installed this just today, and faced same problem, it easly fixable.
So the idea (PS: all this is just my guessing :D) is that you check if client is "floating" then you save it geometry, but clients in floating layout are not floating! and those when you restore them, you restore them without geometry!
```lua
             --if awful.client.floating.get(c) then
                clientData[c]["geometry"] = c:geometry()
                flt = awful.client.property.get(c, "floating")
                if flt ~= nil then
                    clientData[c]["floating"] = flt
                    awful.client.property.set(c, "floating", false)
                end

            --end
```
So just comment this IF / END in restore function

PS: I don't get why geometry get a special if, revelation shoudn't worry about this things, it should just restore EVERYTHING, cause it need to be read only kind of feature.

**Comment by guotsuan** [comment]
Hi @ShadOoW ,

Thanks for the solution. It seems to work. Just let me test for a few days.

I agree with you it is better than revelation just restore everything and shouldn't worry about these things. But revelation works by collecting all clients into 'revelation' tag. the geometry of clients are changed when then fit into the 'revelation' tag. After restoring everything. The geometry of clients usually can be arranged by the layout (for most layouts such as tile). But for floating layout, there is no such arrange function. If revelation did not store the geometry of clients, the geometry of clients restored to floating layout is wrong, since the floating layout does nothing!

Cheers,

**Comment by ShadOoW** [comment]
Hi @guotsuan sorry for repeating, just to clarify:

if Revelation stores all geometry and restore all geometry this will have the following effect:
-In floating layout: we get back client size.
-In other layout: geometry is ignored and it won't matter if it was restored or no.
-floated clients in other layout: will have their original size back.

Conclusion: unless i misunderstood something, it seems like that if statement is actually not needed? I've tested this 3 use-cases for 3 days, didn't notice any bug.

Thank you for maintaining this awesome project!

**Comment by guotsuan** [comment]
Hi,

Thanks for all the test. I'm convinced that restore all geometry should be ok. However let me know if you see anything weird happen.
